name: Noname Scan Job for VAmpI Demo

on:
  push:
    branches: [ "master" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run VAmPI using docker compose
      run: docker compose up -d
      
    - name: Test VAmPI reachability
      run: sleep 5 && curl http://localhost:5002/ --retry 10 --retry-delay 1
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: jfrog.cicd.nonamesec.com/noname-docker-release
        username: ${{ secrets.ACTIVE_REGISTRY_USER }}
        password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

    - name: Noname Security - Active Testing scan
      run: >
          docker run
          --add-host=host.docker.internal:host-gateway
          -e ACTIVE_CONFIG_FILE_PATH=/noname/config.json
          -v $(pwd)/noname:/noname
          -v $(pwd)/openapi_specs:/openapi_specs
          --pull always
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${{vars.ACTIVE_API_URL}}/backend/version)
          scan
          --api-url=${{ vars.ACTIVE_API_URL }}
          --api-token=${{ secrets.ACTIVE_API_TOKEN }}         
          --test-group-id=${{ vars.ACTIVE_TEST_PROFILE_ID }}
          --branch-name=${{ github.head.ref || github.ref_name }}
          --severity-threshold=none
  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps: 
      - name: echo
        run: echo Noname Security Scan passed, deploying ...
      
